# Runs tests and other checks on Pull Requests
name: PR Testing

on:
  pull_request:
    branches:
      - dev
      - preview
  workflow_call:
    inputs:
      timeout:
        description: 'Timeout for runServer (seconds)'
        required: false
        default: 90
        type: number
      client-only:
        description: 'Do not execute runServer'
        required: false
        default: false
        type: boolean

# if a second commit is pushed quickly after the first, cancel the first one's build
concurrency:
  group: pr-testing-${{github.head_ref}}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 8 and 17
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: zulu
          java-version: |
            8
            17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile the mod
        uses: gradle/gradle-build-action@v2
        with:
          arguments: '--build-cache --info --stacktrace assemble'
          generate-job-summary: false

      - name: Attach compilation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-libs
          path: build/libs/
          retention-days: 31

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: '--scan --build-cache --info --stacktrace test'
          generate-job-summary: false

      - name: Run Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: '--build-cache --info --stacktrace spotlessCheck'
          generate-job-summary: false

      - name: Run server for ${{ inputs.timeout }} seconds
        if: ${{ !inputs.client-only }}
        run: |
          mkdir -p run
          echo "eula=true" > run/eula.txt
          echo "stop" > run/stop.txt
          timeout ${{ inputs.timeout }} ./gradlew --build-cache --info --stacktrace runServer 2>&1 < run/stop.txt | tee -a server.log || true
