# Runs tests and other checks on Pull Requests
name: PR Testing

permissions:
  contents: write
  deployments: write
  pull-requests: write

on:
  push:
    branches: ['update/v[0-9]+.[0-9]+.[0-9]+-pr-+[0-9]'] # any semver branche, e.g. update/v1.2.3-pr-4
  pull_request:
    branches: [master, preview]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 8 and 17
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: zulu
          java-version: |
            8
            17

      - name: Run post-build checks
        uses: gradle/gradle-build-action@v2
        id: build_mod
        with:
          arguments: '--scan --build-cache --info --stacktrace build'
          generate-job-summary: false

      - name: Attempt to make a PR fixing spotless errors
        if: ${{ failure() && steps.build_mod.conclusion == 'failure' && github.event_name == 'pull_request' && !github.event.pull_request.draft }}
        run: |
          git reset --hard
          git checkout "${PR_BRANCH}"
          ./gradlew --build-cache --info --stacktrace spotlessApply || exit 1
          git diff --exit-code && exit 1
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git switch -c "${FIXED_BRANCH}"
          git commit -am "spotlessApply"
          git push --force-with-lease origin "${FIXED_BRANCH}"
          gh pr create \
            --head "${FIXED_BRANCH}" \
            --base "${PR_BRANCH}" \
            --title "Spotless apply for branch ${PR_BRANCH} for #${{ github.event.pull_request.number }}" \
            --body "Automatic spotless apply to fix formatting errors, applies to PR #${{ github.event.pull_request.number }}" \
            2>&1 | tee pr-message.log || true
          gh pr comment "${PR_BRANCH}" -F pr-message.log || true
        shell: bash # ensures set -eo pipefail
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          PR_BRANCH: ${{ github.head_ref }}
          FIXED_BRANCH: ${{ github.head_ref }}-spotless-fixes

      - name: Run server for 90 seconds
        run: |
          mkdir -p run
          echo "eula=true" > run/eula.txt
          echo "stop" > run/stop.txt
          timeout 90 ./gradlew --build-cache --info --stacktrace runServer 2>&1 < run/stop.txt | tee -a server.log || true

      - name: Test no errors reported during server run
        run: |
          chmod +x ./scripts/test_no_error_reports
          ./scripts/test_no_error_reports

      - name: Upload Jars
        uses: actions/upload-artifact@v3
        with:
          name: GTExpert-Core
          path: build/libs/*.jar
          retention-days: 31
