# Publishes built jars to distribution platforms
name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mod version'
        required: true
      release_type:
        description: 'Release type'
        type: choice
        default: 'beta'
        options:
          - 'release'
          - 'beta'
          - 'alpha'

env:
  # Version of the mod
  FULL_VERSION: "${{ github.event.inputs.version }}-${{ github.event.inputs.release_type }}"
  # type of release
  NAME: "GTExpertCore"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if tag already exists
        run: |
          if git rev-parse --verify --quiet "v${{ github.event.inputs.version }}"; then
            echo "Version ${{ github.event.inputs.version }} already exists, aborting workflow."
            exit 1
          fi

      - name: Set version
        run: sed -i "s/modVersion.*=.*/modVersion = ${{ env.FULL_VERSION }}/g" gradle.properties

      - name: Commit and push gradle.properties
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to v${{ env.FULL_VERSION }}"
          commit_options: '--no-verify'
          file_pattern: gradle.properties
          tagging_message: "v${{ env.FULL_VERSION }}"

      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: |
            8
            17
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew --build-cache --info --stacktrace build

      - name: Publish to Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "v${{ env.FULL_VERSION }}"
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          curseforge-id: '851103'
          curseforge-token: "${{ secrets.CURSEFORGE_API_KEY }}"
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(sources).jar
            build/libs/*-@(dev).jar
          name: "${{ env.NAME }}-${{ env.FULL_VERSION }}.jar"
          changelog: "Changelog is available [here](https://github.com/${{github.repository}}/releases/tag/v${{ env.FULL_VERSION }})"
          version: "${{ github.event.inputs.version }}"
          version-type: "${{ github.event.inputs.release_type }}"
          loaders: |
            forge
          game-versions: |
            1.12.2
          dependencies: |
            mixin-booter | depends | *
            configanytime | depends | *
            gregtech-ce-unofficial | depends | *
            gregicality-multiblocks | depends | *
            ae2-extended-life | recommends | *
            ae-additions-extra-cells-2-fork | recommends | *
            ender-io-base | recommends | *
            ender-io-machines | recommends | *
            ender-io-endergy | recommends | *
            ender-io-conduits | recommends | *
            ender-io-ae2-conduits | recommends | *
            gregtech-food-option | recommends | *
            chisel | recommends | *
            extracpus | recommends | *
            draconic-evolution | recommends | *
            draconicadditions | recommends | *
            project-red-illumination | recommends | *
          java: |
            8
          retry-attempts: 2
