# Publishes built jars to distribution platforms
name: Publish

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*-release'
      - 'v*-beta'
      - 'v*-alpha'

env:
  # link to the changelog with a format code for the version
  CHANGELOG_LOCATION: "Changelog is available [here](https://github.com/${{github.repository}}/releases/tag/${{github.ref_name}})"
  # type of release
  NAME: "GTExpertCore"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get the version
        run: |
          echo VERSION=$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $1}') >> $GITHUB_ENV
          echo LEVEL=$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $2}') >> $GITHUB_ENV

      - name: Check for Duplicate Tags
        run: |
          if git rev-parse -q --verify "refs/tags/${{ github.ref }}" >/dev/null; then
            echo "Tag already exists. A version bump is required."
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: zulu
          java-version: 17

      - name: Build Project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: '--build-cache --info --no-daemon --stacktrace build'
          generate-job-summary: false
          gradle-home-cache-includes: |
            caches
            jdks
            notifications
            wrapper

      - name: Publish to Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 851103
          curseforge-token: "${{ secrets.CURSEFORGE_API_KEY }}"
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(sources).jar
            build/libs/*-@(dev).jar
          name: 
          version: "${{ env.VERSION }}"
          version-type: "${{ env.LEVEL }}"
          loaders: forge
          game-versions: 1.12.2
          java: 8
          retry-attempts: 2
